matrix_core
int s21_create_matrix(int rows, int columns, matrix_t *result)
Создает матрицу заданного размера.
rows Количество строк (должно быть > 0). columns Количество столбцов (должно быть > 0). result Указатель на структуру, куда будет сохранена созданная матрица. OK (0) в случае успеха, иначе INCORRECT_MATRIX (1).
References allocate_matrix_rows, matrix_struct::columns, INCORRECT_MATRIX, matrix_struct::matrix, OK, matrix_struct::rows.
Referenced by populate_complements_matrix, s21_calc_complements, s21_determinant, s21_mult_matrix, s21_mult_number, s21_sub_matrix, s21_sum_matrix, s21_transpose, START_TEST, START_TEST, START_TEST, START_TEST, START_TEST, START_TEST, START_TEST, START_TEST, START_TEST, START_TEST, START_TEST, START_TEST, START_TEST, START_TEST, START_TEST, START_TEST, START_TEST, START_TEST, START_TEST, START_TEST, START_TEST.
void s21_remove_matrix(matrix_t *A)
Освобождает память, выделенную под матрицу.
Безопасно обрабатывает NULL указатели. После выполнения обнуляет поля структуры. A Указатель на матрицу для удаления.
References matrix_struct::columns, matrix_struct::matrix, matrix_struct::rows.
Referenced by allocate_matrix_rows, perform_inverse_calculation, populate_complements_matrix, s21_determinant, START_TEST, START_TEST, START_TEST, START_TEST, START_TEST, START_TEST, START_TEST, START_TEST, START_TEST, START_TEST, START_TEST, START_TEST, START_TEST, START_TEST, START_TEST, START_TEST, START_TEST, START_TEST, START_TEST.
int s21_eq_matrix(matrix_t *A, matrix_t *B)
Сравнивает две матрицы на идентичность с точностью до S21_EPS.
A Указатель на первую матрицу. B Указатель на вторую матрицу. SUCCESS (1) если матрицы равны, иначе FAILURE (0).
References matrix_struct::columns, is_matrix_valid, matrix_struct::matrix, matrix_struct::rows.
Referenced by START_TEST, START_TEST, START_TEST, START_TEST, START_TEST, START_TEST, START_TEST, START_TEST, START_TEST, START_TEST, START_TEST.