matrix_algebra
int s21_transpose(matrix_t *A, matrix_t *result)
Транспонирует матрицу.
A Указатель на исходную матрицу. result Указатель на транспонированную матрицу. OK (0), INCORRECT_MATRIX (1).
References matrix_struct::columns, INCORRECT_MATRIX, is_matrix_valid, OK, perform_transposition, matrix_struct::rows, s21_create_matrix.
Referenced by perform_inverse_calculation, START_TEST.
int s21_determinant(matrix_t *A, double *result)
Вычисляет определитель матрицы.
A Указатель на матрицу. result Указатель на переменную для сохранения определителя. Исходная матрица A должна быть квадратной. OK (0), INCORRECT_MATRIX (1), CALCULATION_ERROR (2).
References CALCULATION_ERROR, matrix_struct::columns, get_minor_matrix, INCORRECT_MATRIX, is_matrix_valid, matrix_struct::matrix, OK, matrix_struct::rows, s21_create_matrix, s21_determinant, s21_remove_matrix.
Referenced by populate_complements_matrix, s21_determinant, s21_inverse_matrix, START_TEST, START_TEST, START_TEST.
int s21_calc_complements(const matrix_t *A, matrix_t *result)
Вычисляет матрицу алгебраических дополнений.
A Указатель на исходную матрицу. result Указатель на результирующую матрицу. Исходная матрица A должна быть квадратной. OK (0) - успех. INCORRECT_MATRIX (1) - если матрица некорректна. CALCULATION_ERROR (2) - если матрица не квадратная.
References CALCULATION_ERROR, matrix_struct::columns, INCORRECT_MATRIX, is_matrix_valid, OK, populate_complements_matrix, matrix_struct::rows, s21_create_matrix.
Referenced by perform_inverse_calculation, START_TEST, START_TEST.
int s21_inverse_matrix(matrix_t *A, matrix_t *result)
Находит обратную матрицу.
Обратная матрица существует только для квадратных матриц с ненулевым определителем. A Указатель на исходную матрицу. result Указатель на результирующую обратную матрицу. OK (0) - успех. INCORRECT_MATRIX (1) - если матрица некорректна. CALCULATION_ERROR (2) - если матрица не квадратная или ее определитель равен 0.
References CALCULATION_ERROR, INCORRECT_MATRIX, is_matrix_valid, OK, perform_inverse_calculation, s21_determinant.
Referenced by START_TEST, START_TEST.