matrix_arithmetic
int s21_sum_matrix(matrix_t *A, matrix_t *B, matrix_t *result)
Складывает две матрицы.
Складывает матрицу B с матрицей A и сохраняет результат в result. Матрицы A и B должны иметь одинаковые размеры. Функция сама создает результирующую матрицу result. A Указатель на первое слагаемое. B Указатель на второе слагаемое. result Указатель на результирующую матрицу (сумма). Код результата операции: OK (0) - в случае успеха. INCORRECT_MATRIX (1) - если одна из матриц A или B некорректна. CALCULATION_ERROR (2) - если размеры матриц A и B не совпадают.
References CALCULATION_ERROR, matrix_struct::columns, INCORRECT_MATRIX, is_matrix_valid, OK, matrix_struct::rows, s21_create_matrix.
Referenced by START_TEST, START_TEST.
int s21_sub_matrix(matrix_t *A, matrix_t *B, matrix_t *result)
Вычитает одну матрицу из другой.
Вычитает матрицу B из матрицы A и сохраняет результат в result. Матрицы A и B должны иметь одинаковые размеры. Функция сама создает результирующую матрицу result. A Указатель на уменьшаемое. B Указатель на вычитаемое. result Указатель на результирующую матрицу (разность). Код результата операции: OK (0) - в случае успеха. INCORRECT_MATRIX (1) - если одна из матриц A или B некорректна. CALCULATION_ERROR (2) - если размеры матриц A и B не совпадают.
References CALCULATION_ERROR, matrix_struct::columns, INCORRECT_MATRIX, is_matrix_valid, OK, matrix_struct::rows, s21_create_matrix.
Referenced by START_TEST.
int s21_mult_number(matrix_t *A, double number, matrix_t *result)
Умножает матрицу на скалярное значение.
Умножает каждый элемент матрицы A на число number и сохраняет результат в result. Функция сама создает результирующую матрицу result. A Указатель на матрицу для умножения. number Скалярное значение, на которое умножается матрица. result Указатель на результирующую матрицу (произведение). Код результата операции: OK (0) - в случае успеха. INCORRECT_MATRIX (1) - если матрица A некорректна или не удалось создать результирующую матрицу.
References matrix_struct::columns, INCORRECT_MATRIX, is_matrix_valid, OK, matrix_struct::rows, s21_create_matrix.
Referenced by perform_inverse_calculation, START_TEST.
int s21_mult_matrix(matrix_t *A, matrix_t *B, matrix_t *result)
Умножает две матрицы.
A Указатель на первую матрицу-множитель. B Указатель на вторую матрицу-множитель. result Указатель на результирующую матрицу (произведение). OK (0) - успех. INCORRECT_MATRIX (1) - если одна из матриц некорректна. CALCULATION_ERROR (2) - если количество столбцов A не равно количеству строк B.
References CALCULATION_ERROR, matrix_struct::columns, INCORRECT_MATRIX, is_matrix_valid, OK, perform_multiplication, matrix_struct::rows, s21_create_matrix.
Referenced by START_TEST, START_TEST.