s21_matrix.c
static result_code_t populate_complements_matrix(const matrix_t *A, matrix_t *result)
Заполняет матрицу алгебраическими дополнениями.
Эта вспомогательная функция итерирует по каждому элементу исходной матрицы A, вычисляет для него минор и его определитель, а затем записывает итоговое алгебраическое дополнение в матрицу result. Предполагается, что 'result' уже создана и имеет те же размеры, что и 'A'. A Исходная матрица. result Матрица для записи алгебраических дополнений. Код результата операции: OK (0) или код ошибки от вложенных вызовов.
References matrix_struct::columns, get_minor_matrix, matrix_struct::matrix, OK, matrix_struct::rows, s21_create_matrix, s21_determinant, s21_remove_matrix.
Referenced by s21_calc_complements.
static void perform_multiplication(const matrix_t *A, const matrix_t *B, matrix_t *result)
Выполняет вычисление произведения двух матриц и записывает в результирующую.
Эта вспомогательная функция предполагает, что все проверки на валидность и совместимость размеров матриц уже пройдены, и результирующая матрица 'result' уже создана и имеет корректные размеры. A Первая матрица-множитель. B Вторая матрица-множитель. result Матрица для записи результата.
References matrix_struct::columns, matrix_struct::matrix, matrix_struct::rows.
Referenced by s21_mult_matrix.
static result_code_t allocate_matrix_rows(matrix_t *result)
Выделяет память под строки матрицы и инициализирует их нулями.
Вызывается после того, как память под массив указателей уже выделена. В случае ошибки выделения памяти для одной из строк, освобождает всю ранее выделенную память для этой матрицы. result Указатель на матрицу. OK (0) в случае успеха, иначе INCORRECT_MATRIX (1).
References matrix_struct::columns, INCORRECT_MATRIX, matrix_struct::matrix, OK, matrix_struct::rows, s21_remove_matrix.
Referenced by s21_create_matrix.
static int is_matrix_valid(const matrix_t *A)
Проверяет, является ли матрица корректной.
A Указатель на матрицу для проверки. 1 если матрица корректна, иначе 0. Корректная матрица - не NULL, указатель на данные не NULL, размеры строк и столбцов положительные.
References matrix_struct::columns, matrix_struct::matrix, matrix_struct::rows.
Referenced by s21_calc_complements, s21_determinant, s21_eq_matrix, s21_inverse_matrix, s21_mult_matrix, s21_mult_number, s21_sub_matrix, s21_sum_matrix, s21_transpose.
static void get_minor_matrix(const matrix_t *A, int excluding_row, int excluding_col, matrix_t *result)
Создает минорную матрицу, исключая заданную строку и столбец.
A Исходная матрица. excluding_row Индекс исключаемой строки. excluding_col Индекс исключаемого столбца. result Указатель на результирующую минорную матрицу.
References matrix_struct::columns, matrix_struct::matrix, matrix_struct::rows.
Referenced by populate_complements_matrix, s21_determinant.
static void perform_transposition(const matrix_t *A, matrix_t *result)
Копирует элементы из исходной матрицы в транспонированную.
Эта вспомогательная функция предполагает, что обе матрицы, A и result, уже существуют и имеют корректные (взаимно-транспонированные) размеры. A Исходная матрица. result Результирующая (транспонированная) матрица.
References matrix_struct::columns, matrix_struct::matrix, matrix_struct::rows.
Referenced by s21_transpose.
static result_code_t perform_inverse_calculation(const matrix_t *A, double det, matrix_t *result)
Выполняет основную последовательность вычислений для нахождения обратной матрицы.
Эта вспомогательная функция вызывается после того, как исходная матрица проверена и ее определитель вычислен. Она находит матрицу алгебраических дополнений, транспонирует ее и умножает на (1/определитель). A Исходная матрица. det Заранее вычисленный ненулевой определитель матрицы A. result Указатель на результирующую обратную матрицу. Код результата операции: OK (0) или код ошибки от вложенных вызовов.
References OK, s21_calc_complements, s21_mult_number, s21_remove_matrix, s21_transpose.
Referenced by s21_inverse_matrix.
static void perform_sum(const matrix_t *A, const matrix_t *B, matrix_t *result)
static void perform_sub(const matrix_t *A, const matrix_t *B, matrix_t *result)
static void perform_mult_number(const matrix_t *A, double number, matrix_t *result)